language: python
python:
# Travis currently uses pypy version 2.5.0, which fails with this message:
#   RuntimeError: cryptography 1.0 is not compatible with PyPy < 2.6. Please upgrade PyPy to use this library.
#  - "pypy"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
os:
  - linux

before_install:
  - git fetch --unshallow
install:
  - travis_retry pip install pybuilder coveralls
  - travis_retry pyb -v install_dependencies

env:
  PYTHONIOENCODING=UTF-8

script:
    - pyb -v

after_success:
  - coveralls --verbose
