language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

install:
  - pip install pybuilder
  - pip install coveralls
  - pyb install_dependencies
  
script: "pyb verify analyze ; cat '/home/travis/build/ImmobilienScout24/afp-cli/target/reports/cram.err'"

after_success:
  - coveralls --verbose

